import { buildPoseidon } from "circomlibjs";

import { logDebug, logError, logInfo, logWarn } from "@/src/modules/observability/logger";
import { consumeNullifier } from "@/src/modules/database/repository";
import type {
  ComplianceAttestation,
  Severity,
  TransactionPayload,
} from "@/src/modules/transaction/types";

// This interface expects the proof generated by the client using a Groth16 circuit
export interface ZKProofPayload {
  proof: {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
    protocol?: string;
    curve?: string;
  };
  publicSignals: string[];
}

/**
 * Real ZK proof verification using snarkjs Groth16.
 * Validates proof structure and performs cryptographic verification
 * when a verification key is available.
 */
export async function verifyZKProof(proofData: ZKProofPayload): Promise<boolean> {
  const startTime = Date.now();

  try {
    // Structural validation — proof must have correct Groth16 fields
    if (!proofData.proof || !proofData.publicSignals) {
      logWarn("zk.verify.missing_fields", { hasProof: !!proofData.proof, hasSignals: !!proofData.publicSignals });
      return false;
    }

    const { pi_a, pi_b, pi_c } = proofData.proof;

    // Validate Groth16 proof structure
    if (!Array.isArray(pi_a) || pi_a.length < 2) {
      logWarn("zk.verify.invalid_pi_a", { length: pi_a?.length });
      return false;
    }

    if (!Array.isArray(pi_b) || pi_b.length < 2 || !pi_b.every((row) => Array.isArray(row))) {
      logWarn("zk.verify.invalid_pi_b", { length: pi_b?.length });
      return false;
    }

    if (!Array.isArray(pi_c) || pi_c.length < 2) {
      logWarn("zk.verify.invalid_pi_c", { length: pi_c?.length });
      return false;
    }

    if (!Array.isArray(proofData.publicSignals) || proofData.publicSignals.length === 0) {
      logWarn("zk.verify.invalid_public_signals", { length: proofData.publicSignals?.length });
      return false;
    }

    // Validate that all proof elements are valid numeric strings (field elements)
    const allElements = [
      ...pi_a,
      ...pi_b.flat(),
      ...pi_c,
      ...proofData.publicSignals,
    ];

    for (const element of allElements) {
      if (typeof element !== "string") {
        logWarn("zk.verify.non_string_element", { element });
        return false;
      }
      // Field elements should be numeric (decimal) strings
      try {
        BigInt(element);
      } catch {
        logWarn("zk.verify.invalid_field_element", { element: element.slice(0, 20) });
        return false;
      }
    }

    // Attempt real Groth16 verification with snarkjs if verification key is available
    try {
      // @ts-expect-error — snarkjs does not ship TypeScript declarations
      const snarkjs = await import("snarkjs");

      // Build verification key from the proof's public signals
      // In production, this would be loaded from a pre-generated verification_key.json
      // For now, we verify the proof structure is valid and internally consistent

      // Reconstruct the proof in snarkjs format
      const formattedProof = {
        pi_a: pi_a.map(String),
        pi_b: pi_b.map((row: string[]) => row.map(String)),
        pi_c: pi_c.map(String),
        protocol: "groth16",
        curve: "bn128",
      };

      // Check if the proof passes basic snarkjs validation
      // snarkjs.groth16.verify requires a verification key — if we have one stored, use it
      const vKeyPath = process.env.ZK_VERIFICATION_KEY_PATH;
      if (!vKeyPath) {
        logWarn("zk.verify.missing_verification_key", {
          message: "ZK_VERIFICATION_KEY_PATH must be configured before accepting proofs.",
        });
        return false;
      }

      const fs = await import("fs/promises");
      const vKeyRaw = await fs.readFile(vKeyPath, "utf-8");
      const vKey = JSON.parse(vKeyRaw);

      const isValid = await snarkjs.groth16.verify(
        vKey,
        proofData.publicSignals.map(String),
        formattedProof
      );

      const duration = Date.now() - startTime;
      logInfo("zk.verify.groth16_complete", { isValid, durationMs: duration });
      return isValid;
    } catch (e) {
      logError("zk.verify.snarkjs_failed", e);
      return false;
    }
  } catch (error) {
    logError("zk.verify.failed", error);
    return false;
  }
}

export async function generatePoseidonNullifier(
  payload: TransactionPayload,
  severity: Severity
): Promise<string> {
  const poseidon = await buildPoseidon();

  // Convert strings to bigints for Poseidon input
  const fromStr = payload.from.replace("0x", "").slice(0, 16);
  const toStr = payload.to.replace("0x", "").slice(0, 16);

  const fromBigInt = BigInt("0x" + fromStr);
  const toBigInt = BigInt("0x" + toStr);
  const severityInt = severity === "critical" ? 3n : severity === "high" ? 2n : severity === "medium" ? 1n : 0n;
  const timestampBigInt = BigInt(Math.floor(Date.now() / 60000)); // Minute-level granularity

  const hash = poseidon([fromBigInt, toBigInt, severityInt, timestampBigInt]);
  return poseidon.F.toString(hash);
}

export async function recordComplianceAttestation(
  payload: TransactionPayload,
  severity: Severity,
  zkPayload?: ZKProofPayload
): Promise<{
  accepted: boolean;
  record: ComplianceAttestation;
}> {
  if (zkPayload) {
    const isValid = await verifyZKProof(zkPayload);
    if (!isValid) throw new Error("Invalid ZK Proof provided.");
  }

  // Use real ZK-friendly Poseidon hash instead of SHA256
  const nullifierHash = await generatePoseidonNullifier(payload, severity);

  const record: ComplianceAttestation = {
    attestationId: `att_${nullifierHash.slice(0, 10)}`,
    nullifier: nullifierHash,
    policy: severity === "critical" ? "policy-review-required" : "policy-screened",
    createdAt: new Date().toISOString(),
    persistent: Boolean(process.env.DATABASE_URL),
  };

  const accepted = await consumeNullifier(nullifierHash, payload, severity);

  logDebug("zk.attestation.recorded", {
    attestationId: record.attestationId,
    accepted,
    severity,
    persistent: record.persistent,
  });

  return {
    accepted,
    record,
  };
}
